name: movie_browser
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5+1
  go_router: ^16.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/movie.json
    - assets/empty.png
    - assets/second_movie.json
    - assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
